import { AmplifyRuntime } from '@/components/aws/AmplifyRuntime';
import Providers from '@/providers';
import { Header } from '@/components/header';
import './global.css';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AmplifyRuntime />
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
